### ISSUE TITLE
Links nos títulos dos projetos

### ISSUE THREAD

**Issue by lubien** [globocom/opensource#12]
Uma primeira coisa que tomou minha atenção na página de projetos foi que os títulos não eram links quando tentei clicar.

![image](https://user-images.githubusercontent.com/9121359/46673474-39405480-cbb0-11e8-8cba-278e09c658e4.png)

Não sei se foi uma escolha de projeto mas vocês acreditam que poderiam ser usados links no título eu poderia fazer uma PR.

**Comment by guilhermebr** [comment]
@lubien o PR é bem vindo sim, obrigado!
