### ISSUE TITLE
Copyright ano nao é dinâmico

### ISSUE THREAD

**Issue by davidsonsimoes** [globocom/opensource#13]
O Copyright do footer esta como "Globo.com 2018" sendo o ano um texto direto no código, minha dúvida é, existe a necessidade do ano ser dinâmico? Se for preciso posso abrir um PR com um script para essa data do footer.

**Comment by arturfsousa** [comment]
Seria dinâmico sim @davidsonsimoes. O PR seria muito bem vindo.
