### ISSUE TITLE
Documentar variáveis de ambiente

### ISSUE THREAD

**Issue by lubien** [globocom/opensource#17]
O primeiro desafio desconhecido que tive durante minha ultima PR foi encontrar o motivo pelo qual os projetos não eram carregados. Verifiquei que era a falta do token de acesso pessoal na variável GATSBY_GITHUB_TOKEN.

Acredito que ajuda para futuros colaboradores documentar a necessidade do token. 

Talvez o local mais apropriado seria no próprio README na área onde se explica o processo para desenvolvimento.

Também seria necessário descrever como obter o token, que poderia-se utilizar de um link para o tutorial oficial do GitHub, mas precisa também saber quais os escopos do token. 

Eu poderia fazer uma PR com esta adição, só preciso saber os escopos mesmo.

**Comment by TiagoDanin** [comment]
Tiver o mesmo problema. Outra ponto é que no README os camandos de instalação são para roda o Makefile, poderíamos usar o yarn diretamente sem a necessidade do Makefile.

**Comment by lubien** [comment]
Realmente. Talvez a utilização do Makefile seja escolha da equipe. Você poderia abrir uma issue para que isso seja discutido separadamente?

**Comment by TiagoDanin** [comment]
:+1: Feito #18

**Comment by arturfsousa** [comment]
Verdade @lubien. Obrigado pelo feedback. Estamos portando os requests para nossa api interna, logo não precisaremos mais de um token. Obrigado pela contribuição.
