### ISSUE TITLE
[Discussão] Usar o Yarn ao invés do Makefile

### ISSUE THREAD

**Issue by TiagoDanin** [globocom/opensource#18]
Atualmente o projeto tem um Makefile que é usado como atalho para executar comandos do yarn, dito isso... não seria melhor documenntar a instalação e utilização com o Yarn.

**Comment by arturfsousa** [comment]
olá @TiagoDanin já está documentado no primeiro parágrafo da seção `Develoment` em https://github.com/globocom/opensource/blob/master/README.md
