### ISSUE TITLE
Membros não carregam

### ISSUE THREAD

**Issue by thayannevls** [globocom/opensource#23]
Rodei a aplicação localmente como indicado no readme e coloquei o meu token do github, os Projetos a aplicação conseguiu carregar, mas os *membros* da tela `nosso-time` não, fica apenas aparecendo `Carregando membros` e sem erros no console.

Eu pretendia contribuir para tela `nosso-time`mas sem aparecer os membros fica difícil, poderia me indicar se estou fazendo algo errado? Ou se é necessário algum passo a mais para isso.

Obrigada desde já.

**Comment by TiagoDanin** [comment]
Qual seu OS ? Tentou usando env-cmd ?
No bash você pode importar da seguinte formar:
```bash
 $ export GATSBY_GITHUB_TOKEN=1234567890MYTOKENGITHUB
```

**Comment by thayannevls** [comment]
Oi Tiago, descobri o problema, foi porque não dei acesso de admin para ler organizações no meu token. Bem que poderia ter no readme dizendo as permissões necessárias pro token, eu poderia adicionar isso no readme?

**Comment by guilhermebr** [comment]
@thayannevls pode sim! obrigado
