### ISSUE TITLE
Show user stats on hacktoberfest challenge

### ISSUE THREAD

**Issue by thayannevls** [globocom/opensource#28]
Como o participante pode se logar no site com o usuário do github, acho que daria pra fazer algo parecido com o hacktoberfest do [digitalocean](https://cdn-images-1.medium.com/max/2000/1*BikgIwoeUXl0M61U6FBHng.png).

A diferença era que seria preciso filtrar para pegar PRs referentes apenas os repositórios do *globocom*. Dito isso acho que poderia dividir em duas tasks que seria fazer a query pro github API e a outra de criar uma visualização pra isso na página.

O que acham?

**Obs**: Se vocês preferem que as issues sejam em inglês, posso dar edit.

**Comment by arturfsousa** [comment]
Olá @thayannevls e @FannyVieira, estamos trabalhando nesta feature. Logo estaremos subindo a atualização. Obrigado pelo report.

[]s
