### ISSUE TITLE
Using CSS in JS

### ISSUE THREAD

**Issue by lopesboa** [globocom/opensource#33]
Ola, o que vocês acham de usar o css em arquivos js, usando a lib styled-component.
Estou a disposição se for necessário para fazer essas alterações.

**Comment by arturfsousa** [comment]
Olá @lopesboa tudo bem? Acho uma idéia legal sim. Como não tinha experiência ainda com essas libs de CSS-IN-JS decidi por usar apenas `css-modules` mesmo. `css-modules` resolve o problema de escopo de namespaces e você continua escrevendo css puro mesmo.

Estamos agora passando por um refactoring do layout como um todo então provável que a UI mude bastante, logo podemos fazer essas mudanças utilizando `styled-components` também.

Por enquanto vamos aguardar a equipe de UX terminar o trabalho e voltamos nisso.

Obrigado pelo interesse.
