### ISSUE TITLE
O portal está reparado para o hacktoberfest 2019? 

### ISSUE THREAD

**Issue by izontm** [globocom/opensource#36]
Ao tentar informar o endereço no botão [CADASTRAR ENDEREÇO DE ENVIO], é apresentado um erro:
```
Houve uma falha na alteração dos seus dados. Tente novamente.
```
O que ocorre é um erro 404 na rota:
```
https://opensource.globo.com/subscribe
```

**Comment by guilhermebr** [comment]
@izontm estamos terminando de subir a edição 2019, mas sua inscrição ja esta registrada, assim que liberar o form informaremos por email para completar o cadastro

**Comment by arturfsousa** [comment]
Tudo regularizado, em breve você verá o form para alteração dos seus dados. Keep hacking...
