### ISSUE TITLE
Migração do Google analytics

### ISSUE THREAD

**Issue by davidsonfellipe** [globocom/opensource#4]

**Comment by davidsonfellipe** [comment]
@fsouza chico, ainda está em minha conta do google analytics, posso transferir para fss@corp.globo.com?

**Comment by fsouza** [comment]
@davidsonfellipe pode transferir.

**Comment by rafaelfragosom** [comment]
@davidsonfellipe Qual o status dessa issue?

**Comment by davidsonfellipe** [comment]
@rafaelfragosom percebi que ainda tá comigo, qual teu email?

**Comment by rafaelfragosom** [comment]
@davidsonfellipe Falei com o pessoal da Globo e pedi um e-mail de uma conta interna, que é melhor que usar o meu. Eu te passo no privado assim que receber.

**Comment by rafaelfragosom** [comment]
@davidsonfellipe Estamos gerando um no e-mail interno aqui, então você já pode remover do seu e-mail. Valeu!
