### ISSUE TITLE
Package manager

### ISSUE THREAD

**Issue by lubien** [globocom/opensource#40]
Pelo readme.

> You need to have nodejs and yarn installed

Noto a presença de um `yarn.lock` não seria interessante restringir ou pelo menos avisar a preferência? 

Além disso, os comandos `make *` usam yarn.

```sh
 λ opensource make setup
make: yarn: Command not found
make: *** [Makefile:26: setup] Error 12
```

Eu poderia até mesmo criar um script que descobre se a pessoa tem yarn e usa ou fallback para npm, caso seja de interesse do repo.

**Comment by arturfsousa** [comment]
Olá @lubien. Essa nota no `README` mas o campo `engines` no package.json deixa bem clara a preferência pelo uso do `yarn` como package manager. Contribuidores podem utilizar o package manager de sua preferência, porém o que não queremos é ter que manter 2 arquivos de lock diferentes: `yarn.lock` e `package-lock.json`, como você pode ver em projetos como [react](https://github.com/facebook/react) e [gatsby](https://github.com/gatsbyjs/gatsby) que mantém apenas o `yarn.lock`.

Você pode utilizar o próprio `Makefile` para utilizar o package manager instalado na máquina, vou colocar o exemplo no PR.
