### ISSUE TITLE
Bug no campo de e-mail do formulário de finalização do HACKTOBERFEST 2019

### ISSUE THREAD

**Issue by Koalapvh13** [globocom/opensource#47]
Tentei solicitar minha camisa do Hacktoberfest 2019 esta tarde mas, ao acessar o formulário de solicitação, deparei-me com um pequeno bug no campo de e-mail:

![image](https://user-images.githubusercontent.com/25057248/66708974-86598800-ed28-11e9-8204-c4ccdcd97b23.png)

Ao abrir o formulário, nota-se que o campo e-mail apresenta automaticamente uma mensagem de erro (que mais parece ser um teste que subiu para produção.😅😅) e, mesmo que seja fornecido um email válido, é solicitada a correções. O maior problema nessa situação é o fato deste erro impedir o envio das informações.

Após "debugar" mentalmente o componente [HacktoberFestProgress.js](https://github.com/globocom/opensource/blob/master/src/components/HacktoberFestCall/HacktoberFestProgress.js), depreendi que ao retirar a linha 165 pode ser que o erro seja sanado. Por isso, enviei o PR #46 . Contudo, por estar impossibilitado de testar a solução, peço que a comunidade possa estar comprovando se meu PR resolve o problema.

Vida longa e próspera. 🖖🖖

**Comment by arturfsousa** [comment]
Olá @Koalapvh13 era um teste mesmo. A funcionalidade de envio do formulário ainda está em desenvolvimento. 

Você estaria interessado em implementar a parte de validação corretamente? Basta salvar esses campos no estado do component react e ao clicar no botão salvar verificar se eles estão vazios e passar a prop `errorText`: Campo obrigatório.

O que acha?

**Comment by IsraelSampaio** [comment]
Queria ajudar. posso @arturfsousa ?

**Comment by Koalapvh13** [comment]
Perdão pelo vácuo @arturfsousa , estou meio aperreado essa semana e não vou poder ajudar. @IsraelSampaio se você puder ajudar seria bem bacana...

**Comment by arturfsousa** [comment]
Pode sim @IsraelSampaio. Você conseguir fechar até amanhã? Porque estamos precisando terminar essa feature para o site.

[]s

**Comment by IsraelSampaio** [comment]
@arturfsousa Então eu mandei a validação dos campos, falta a comunicação com api.
