### ISSUE TITLE
(Hacktoberfest): Prize form does not work

### ISSUE THREAD

**Issue by MarcosEllys** [globocom/opensource#53]
When I have completed the form and click submit, the form does not change

## Form

![image](https://user-images.githubusercontent.com/6751242/66751300-1b619b80-ee65-11e9-824a-1e41715026f2.png)

## Another infos

Maybe duplicate with 

- #36 (O portal está reparado para o hacktoberfest 2019?)
- #47 (Bug no campo de e-mail do formulário de finalização do HACKTOBERFEST 2019)

**Comment by arturfsousa** [comment]
It's fixed now. You will be able to see the form again soon. Thanks for the report.
