### ISSUE TITLE
Clarificação sobre condições

### ISSUE THREAD

**Issue by viniciusbds** [globocom/opensource#55]
A alteração feita em #43 não está funcionando na prática, pois o [site](https://opensource.globo.com/hacktoberfest/) ainda está mostrando a versão antiga:

**Os 200 primeiros inscritos ganharão uma
camiseta exclusiva a ser entregue dentro
do território brasileiro.**

e não a nova:

**Os 200 primeiros inscritos, 
que completarem os requisitos mínimos, 
ganharão uma camiseta exclusiva...**

**Comment by arturfsousa** [comment]
Feito
