### ISSUE TITLE
Como posso saber se serei um dos 200 premiados?

### ISSUE THREAD

**Issue by tclemos** [globocom/opensource#59]
Completei o desafio abrindo no mínimo 2 PRs e tendo pelo menos 1 deles aceito, porém, não sei estou dentro dos 200 que receberão o prêmio.

![image](https://user-images.githubusercontent.com/1298871/67615102-3d7ce700-f79e-11e9-8b0f-a0f38d5e2c54.png)

**Comment by marcelometal** [comment]
Olá @tclemos , não se preocupe, você está dentro dos primeiros 200. Logo vamos mostrar na interface. Happy hack!
