### ISSUE TITLE
Add anchor (<a>) tag with documentation on Home and "Projetos" page

### ISSUE THREAD

**Issue by AltheusV** [globocom/opensource#80]
Hey, I noticed that some projects are missing a direct link for the project's documentation, like thumbor, clappr, huskyci and megadraft. 

They only have a link for the repository.

I think it would be a good enhancement for the page's layout. 

What you guys think? Can I work on that?

![image](https://user-images.githubusercontent.com/30200769/95370810-bb52d900-08af-11eb-9142-757829f02599.png)

**Comment by marcelometal** [comment]
Hi @AltheusV,

there is no link because it was not added in database; I just added...

Please choose another issue:
https://github.com/search?q=label%3Ahacktoberfest+state%3Aopen+type%3Aissue+user%3Aclappr+user%3Afastlane-queue+user%3Agaleb+user%3Aglobocom+user%3Athumbor+user%3Atsuru
